#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, limitSwitch,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task stopAllMotors(){
  motor[rightMotor] = 0;
  motor[leftMotor] = 0;
}

task main(){
  while (SensorValue[pushBtn] == 0 && vexRT[Btn7U] == 0){
    while(SensorValue(sonarSensor) < 55 || SensorValue(sonarSensor) == -1 ){
      motor[rightMotor] = -60;
      motor[leftMotor] = 60;
      wait1Msec(535);
    }
    if(SensorValue(lightSensor) > 300){
    	StartTask(stopAllMotors);
  	}
  	else{
    	motor[rightMotor] = 127;
    	motor[leftMotor] = 127;
  	}
	}
}