#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl11, limitSwitch,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task stopAllMotors(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;
	motor[clawMotor] = 0;
}

task LCD()
{
  clearLCDLine(0);
  clearLCDLine(1);

  bLCDBacklight = true;
  displayLCDPos(0,1);
  displayNextLCDString("Verkefni nr: 4");

  displayLCDPos(1,1);
  displayNextLCDString("Version: 1.0.0");
}

task main()
{
	StartTask(LCD);
	while (SensorValue[pushBtn] == 0 && vexRT[Btn7U] == 0){
		motor[leftMotor] = vexRT[Ch3] / 2;
		motor[rightMotor] = vexRT[Ch2] / 2;

		if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[limitSwitch] == 0){
				motor[armMotor] = 60;
			}
		}
		else if(vexRT[Btn5U] == 1)
		{
				motor[armMotor] = -60;
		}
		else
		{
			motor[armMotor] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[clawMotor] = 60;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[clawMotor] = -60;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
	StartTask(stopAllMotors);
}
