#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in7,    armSensor,      sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 63;


task stopp()
{
	while(true){

	}
}

void stopMotors(){
	motor[rightMotor] = 0;
 	motor[leftMotor] = 0;
 	wait1Msec(1500);
}

void claw(int value){
	if(value == 60){
		motor[clawMotor] = 60;
		wait1Msec(1000);
	}
	else{
		motor[clawMotor] = -60;
		wait1Msec(1000);
	}
	motor[clawMotor] = 0;
}

void followLine()
{
	int threshold = 2300;
	while(true)
	{
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
		if(SensorValue(sonarSensor) < 12)
		{
			break;
		}
	}
}

void turnaround()
{
	motor[leftMotor] = 60;
	motor[rightMotor] = -60;
	wait1Msec(1000);
}

task main()
{
//	StartTask(stopp);

	claw(60);

	while(SensorValue(sonarSensor) > 9)
	{
		followLine();
	}

	stopMotors();

	claw(-60);

	while(SensorValue(armSensor) < 3500)
	{
		motor[armMotor] = -30;
	}
  	motor[armMotor] = 0;

	turnaround();

	while(SensorValue(sonarSensor) > 9)
	{
		followLine();
	}

	stopMotors();

	while(SensorValue(armSensor) > 250)
	{
		motor[armMotor] = 30;
	}
  	motor[armMotor] = 0;

	claw(60);

	while(true){}
}
